### ISSUE TITLE
Reply box styled incorrectly and partially enabled during deletion

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-client#1286] opened 2021-09-01 15:30 UTC
The reply box styling does not match the prototypes while a deletion is underway; in both deletion interaction flows, it looks like the reply box is enabled (but sitting on a grayed out background). After clicking repeatedly, I can sometimes type into the reply box.

# Steps to reproduce

1. Delete a source (files and messages or source account)

# Expected behavior

Styling of reply placeholder matches prototypes

# Actual behavior
Illustrated below, note how I can type into the reply box while a deletion operation is underway.

![Client with test data](https://user-images.githubusercontent.com/213636/129646256-6696ee12-8625-49ec-acf7-7c746928fc70.jpg)

**Comment by conorsch** [comment] 2021-09-23 23:49
Tried reproducing this while reviewing #1301, and it's tricky (but possible) to do so in the dev env. Will try again with a staging env, so the tor connection is in play, and the round-trip provides sufficient time to reproduce the graphical quirk.

**Comment by conorsch** [comment] 2021-09-24 19:11
In a staging environment, with connections going over Tor, I certainly had more time to attempt reproduction, but still struggled. Here's a video of my failing to reproduce the issue (the reply box does not accept clicking during deletion, but does after):

![sd-app-deletion-ghosting-cannot-reproduce](https://user-images.githubusercontent.com/657862/134727765-8c0e44ce-bddd-4b04-af1f-ff7591418ff2.gif)

The fact that I couldn't easily reproduce it doesn't mean it's not a bug, I'll certainly keep trying. One problem I was able to see is that the message pane showed the to-be-deleted messages and attachments during the deletion pending operation, then updated to correctly show no messages after completion:

![sd-app-deletion-ghosting-orthogonal-issue](https://user-images.githubusercontent.com/657862/134727958-d5c08593-b724-4617-a662-db9965cce880.gif)

Adding this info simply as more corroboration that the flow isn't quite what we want, will continue to test.

**Comment by conorsch** [comment] 2021-09-27 23:30
@creviera mentioned she has a potential fix for this problem, so I'm standing by to review the diff. In the meantime, I'll investigate #1290.

**Closed** 2021-09-29 22:39 UTC
Labels: bug, release QA

**Comment by creviera** [comment] 2021-11-01 16:00
Related issue about not deleting the draft reply in the "Compose a reply" textbox: https://github.com/freedomofpress/securedrop-client/issues/1303
