### ISSUE TITLE
signin button in offline mode is showing different size

### ISSUE THREAD

**Issue by kushaldas** [freedomofpress/securedrop-client#1093] opened 2020-05-14 11:23 UTC
The singin button is showing different size during offline mode. Here is a screenshot.

![signin](https://user-images.githubusercontent.com/272303/81928404-d07a5300-9602-11ea-8a7e-3023e5051f97.png)

It is also resizing itself when I am moving the mouse pointer (during the test run I can see that), Here is GIF recording.

![signin_button_size](https://user-images.githubusercontent.com/272303/81928746-64e4b580-9603-11ea-91f0-e2e07e6210d5.gif)

**Comment by eloquence** [comment] 2021-12-10 00:39
Cannot reproduce in Qubes. This may be a dev-env only issue, or it may have been resolved since this issue was filed. Closing for now.

![cclient](https://user-images.githubusercontent.com/213636/145497627-e785aa76-774a-47bf-823d-9b351415289a.png)

**Closed by eloquence** 2021-12-10 00:39 UTC
Labels: component/UI
