### ISSUE TITLE
Failed replies should have visual clue

### ISSUE THREAD

**Issue by kushaldas** [freedomofpress/securedrop-client#435] opened 2019-06-25 15:45 UTC
If the client fails to send a reply to a source, it should mark it with some visual clue in the UI. So, that the user can click and try to resend.

Example: when sms or Signal fails to send the message, and then we can retry to send.

**Comment by redshiftzero** [comment] 2019-06-25 16:00
duplicate of #365

**Closed by redshiftzero** 2019-06-25 16:00 UTC
