### ISSUE TITLE
Populate active source conversations first

### ISSUE THREAD

**Issue by rmol** [freedomofpress/securedrop-client#1042] opened 2020-04-01 22:47 UTC
When syncing, it would feel more responsive to see the most recently active sources' conversations populate first.

**Comment by eloquence** [comment] 2020-04-01 22:50
Is this a dupe of #883?

**Comment by rmol** [comment] 2020-04-01 22:52
Why yes it is. I searched and actually even paged through the open issues, thinking surely this must have been noted already, but somehow missed that. :man_facepalming:

**Closed** 2020-04-02 00:24 UTC
