### ISSUE TITLE
Only conversation deleted from source

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#901] opened 2020-03-09 23:19 UTC
# STR
(Having a hard time repro'ing)

1. Delete source until you see "Failed to delete at sever" message in the error bar
2. Try to delete a different source
3. Try to delete the source that originally failed again

# Expected

For sources to either delete or not delete with the "Failed to delete at server"

# Actual

One of the sources looked like only the conversation was deleted, see

![Screenshot from 2020-03-09 16-02-28](https://user-images.githubusercontent.com/4522213/76265317-6a97d680-6221-11ea-9d64-81cf1d36dbe4.png)

**Comment by creviera** [comment] 2020-03-09 23:21
Saw this in the logs:

```
2020-03-09 15:54:29,998 - securedrop_client.storage:134(update_source_key) ERROR: New source data lacks key fingerprint
2020-03-09 15:55:02,451 - securedrop_client.queue:131(process) ERROR: JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-03-09 15:55:12,366 - securedrop_client.queue:131(process) ERROR: JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-03-09 15:55:27,608 - securedrop_client.queue:131(process) ERROR: JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by rmol** [comment] 2020-03-18 18:45
I'm also having a hard time triggering this error. I cleaned out dev and staging environments and never got the error message. Deletions just queued up and worked. :man_shrugging:

**Comment by redshiftzero** [comment] 2020-03-18 22:59
I also can't reproduce - I just tried to reproduce this by having the source deletion endpoint `abort(404)` 50% of the time, and then following the STR above, but the client worked in that scenario with no empty source conversations.

If anything, I strongly suspect that this was due to the JSONDecodeError (:thinking:), tracked in #900 so going to close this one.

**Closed by redshiftzero** 2020-03-18 22:59 UTC
Labels: bug
