### ISSUE TITLE
Submitted files not showing in client + "Failed" messages didn't?

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-client#909] opened 2020-03-11 03:15 UTC
## Problem n°1
I submitted a message and a file as a new source, to the Jenntastic instance. On the workstation client, both came in quickly and clearly. 
 
![image](https://user-images.githubusercontent.com/8262612/76378177-0e5cb180-630a-11ea-975d-fd961cfc510b.png)

..
After the first journalist reply, I sent more files and messages. None appeared in the client. However, I was still able to send messages back to the source from the client, and those messages appeared to me in the Source UI. 

When I went to check the Journalist web UI to see if the server had received things, indeed it had:
![image](https://user-images.githubusercontent.com/8262612/76378116-e1100380-6309-11ea-915c-1856fe4bba8d.png)

...
Conor theorized it could be a loss of the connection to the SD server, however I was still able to send replies to the source, from the client. 

![image](https://user-images.githubusercontent.com/8262612/76378392-81662800-630a-11ea-813c-238ac577671e.png)

![image](https://user-images.githubusercontent.com/8262612/76378494-b96d6b00-630a-11ea-88fb-32a27e832422.png)

Note: I had deleted one reply in the Source UI, it is below—and I will follow a separate issue in the sd repo, for the dialog jankery:
![image](https://user-images.githubusercontent.com/8262612/76378537-d99d2a00-630a-11ea-8b77-5879ad446b0f.png)

## Problem n°2
See in the above screenshots, that the Source UI shows `moo to you` and `once more` both as received, however the Client shows them as failed. That feels like a biggy problem to me.

**Comment by eloquence** [comment] 2020-03-11 04:44
Thanks for the detailed report, Nina! I'm  unable to reproduce this with the latest client (`master`, not the nightly) in Qubes running against my own prod instance. Note for other testers: Nina's workstation is configured with v2 onion services, mine with v3.

I advised you to not restart your laptop after the last rebuild, but given this behavior, I would recommend it, to exclude the possibility that some VMs are in an outdated state, before testing again.

**Comment by redshiftzero** [comment] 2020-03-18 17:01
Problem 1 here should be resolved by #937, problem 2 is still outstanding

**Comment by zenmonkeykstop** [comment] 2024-02-08 19:26
no.2 is a known issue with replies (also related to https://github.com/freedomofpress/securedrop-client/issues/653). Closing this ticket.

**Closed by zenmonkeykstop** 2024-02-08 19:26 UTC
Labels: bug, needs/reproducing
