### ISSUE TITLE
Client hangs on startup in Qubes in sd-svs

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop-client#519] opened 2019-08-06 14:10 UTC
On the latest nightly build, 0.0.9-dev-20190806-050249, the client completely hangs and the Source/Submissions list is not updated. The window becomes unresponsive and must be killed via Terminal.

At first glance, there is no useful information in the logs, the log contents seem consistent with normal functional behavior:
```
user@sd-svs:~$ tail -f .securedrop_client/logs/client.log 
2019-08-06 10:03:43,983 - securedrop_client.storage:90(get_remote_data) INFO: Fetched 3 remote submissions.
2019-08-06 10:03:43,983 - securedrop_client.storage:91(get_remote_data) INFO: Fetched 2 remote replies.
2019-08-06 10:03:43,984 - securedrop_client.logic:272(completed_api_call) INFO: Completed API call. Cleaning up and running callback.
2019-08-06 10:03:43,998 - securedrop_client.storage:162(update_sources) DEBUG: Added new source e1b0d84b-4052-414e-9b49-5f18ee8b8cd5
2019-08-06 10:03:43,999 - securedrop_client.storage:162(update_sources) DEBUG: Added new source ae65afe2-2139-4192-b869-ad0ec8f7fa94
2019-08-06 10:03:44,009 - securedrop_client.storage:227(__update_submissions) DEBUG: Added new submission f53ad2a4-f9e7-444e-9947-68d807108177
2019-08-06 10:03:44,016 - securedrop_client.storage:227(__update_submissions) DEBUG: Added new submission 8b1e5ca6-687c-4a24-ba1e-1782d135b7bf
2019-08-06 10:03:44,018 - securedrop_client.storage:227(__update_submissions) DEBUG: Added new submission 0362d047-e8d1-43e8-ac54-d7384f1dd9fd
2019-08-06 10:03:44,026 - securedrop_client.storage:280(update_replies) DEBUG: Added new reply f1afe9c8-faa7-4d5c-ab58-952795b08e50
2019-08-06 10:03:44,030 - securedrop_client.storage:280(update_replies) DEBUG: Added new reply 070a192c-5385-4dc8-a999-2b670a885bca
```

**Comment by creviera** [comment] 2019-08-06 18:18
After rebooting, and running `make all`, I hopped into `sd-svs` an ran `securedrop-client` and noticed the recent source list changes I made yesterday were **NOT** showing up, so it looked like the sd-svs did not get the nightly for some reason. 

After running `securedrop-update` in dom0, I was able to get the latest nightly build on sd-svs. I could not repro this issue. I see the latest changes loading in the client, the source list is being populated, and conversations are loading.

**Comment by creviera** [comment] 2019-08-06 18:20
More info:

I'm running in a production environment (see https://github.com/freedomofpress/securedrop-client#production-environment), but instead of pointing the client to the SF test servers, I am pointing it my own test servers.

**Comment by conorsch** [comment] 2019-08-08 18:27
I'm not able to reproduce the problem reported. Testing on with version `0.0.9-dev-20190808-050320` of `securedrop-client`, I'm able to load the Client and open submissions in DispVM. On the first login of the client app, there's a bit of a wait for the conversation view to draw (~20s), but that doesn't seem to be a new issue. On subsequent logins, the conversation view draws much more quickly (~5s). 

@creviera given that neither of us is able to reproduce, I'm inclined to close, until we get more info from @emkll. Over to you for the final call.

**Comment by creviera** [comment] 2019-08-08 18:51
(I tested version `0.0.9-dev-20190807-050248`)

**Comment by redshiftzero** [comment] 2019-11-07 23:30
I'm gonna close this - @emkll if you see it again please re-open and we can take another look

**Closed by redshiftzero** 2019-11-07 23:30 UTC
Labels: bug, needs/reproducing
