### ISSUE TITLE
Replies are sometimes out of order

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#1445] opened 2022-03-16 01:38 UTC
## Description

Pending replies are sometimes not properly ordered. Could be related to recent changes introduced in: https://github.com/freedomofpress/securedrop-client/pull/1432 (will follow up here to confirm that).

## Steps to Reproduce

In Qubes, I tested by:
1. Sending the reply message: "1"
2. Sending the reply message: "2"
3. Stopping the network VM
4. Sending the reply message: "3"

## Expected Behavior

For the pending reply widget with the message "3" to show up at the bottom of the conversation view.

## Actual Behavior

The pending reply widget with the message "3" shows up in between "1" and "2". Once I connect to a network, the reply widget goes from pending to successful, and then it's reordered properly (it's moved to the bottom of the conversation in this case).

**Comment by creviera** [comment] 2022-03-16 17:33
Note that I was unable to repro before https://github.com/freedomofpress/securedrop-client/pull/1432

**Comment by rocodes** [comment] 2022-03-16 17:37
Thanks for filing, I think I can figure out what's happening. First of all, can you confirm that

a) you can't reproduce this for a source where you haven't run safe-delete since the changes landed (So follow your STR but make sure you haven't run safe-delete for this source, and let me know if you can still reproduce the issue)
b) you can't reproduce this for a source where you've run safe-delete, then waited > 1 full sync before trying your STR?

it looks like a database conflict is locking the database (ugh, I kind of saw this coming, not with this issue but just in general https://github.com/freedomofpress/securedrop-client/issues/1440 :( 

I'm seeing this in the logs:
```
2022-03-16 13:22:09,358 - securedrop_client.gui.widgets:3156(on_reply_sent) DEBUG: Could not refresh instance '<DraftReply at 0x6e7f1989b710>'
```
which I think is the result of something a little more serious:  

```
  Failed to send reply 490caafd-82e5-4d12-8ff0-25a50092452e for source 3ccd14df-61be-482e-9b17-25e958335c55 due to Exception: (sqlite3.OperationalError) database is locked
2022-03-16 13:30:38,013 - securedrop_client.logic:660(on_sync_failure) WARNING: sync failure: (sqlite3.OperationalError) database is locked
```
which... I think is maybe the result of a problem in the source's table, specifically with `last_updated`. Still puzzling this out though.

**Comment by rocodes** [comment] 2022-03-18 01:31
Updates:
- There are two separate issues here, the "replies sometimes out of order" (original issue Allie filed) and the database conflict (the logs I shared, introduced at the same time but a separate issue)
- The "replies out of order" can be reproduced intermittently with the STR Allie provided, and I think that re-introducing some of the timestamp logic that we removed will remediate it
- I have a local fix for the database conflict errors, which were related to improper incrementing of some of the submission/reply attributes during the '[skip downloading stale/recently-deleted messages](https://github.com/freedomofpress/securedrop-client/blob/a29c2172e65e03d66897bd7728ec958d2bf37a3c/securedrop_client/storage.py#L387)' logic
- It will take me a little bit more time to figure out some of the finer points of draft-reordering-plus-local-deletion-plus-network-failures-all-together, because it's a little gnarly, but thankfully I think that that _very_ much edge case (someone deletes all the files for a source then decides to message that source within 15 seconds while experiencing a network outage is a... very specific scenario)
- None of this should affect the [source deletion changes](https://github.com/freedomofpress/securedrop-client/pull/1441)

I'm undecided about whether I'll fix this in one PR or two, I'm going to spend some more time looking at it over the next few days, but have my bearings and just wanted to leave an update.

**Closed** 2022-03-31 22:33 UTC
