### ISSUE TITLE
"Last Refresh: X hours ago" doesn't go away upon reconnection

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-client#1000] opened 2020-03-25 02:27 UTC
## Description
I'm me, so my internet sucks. 
My connection drops. It comes back. 
The error message goes away.
I see the sync widget sync.
The "Last Refresh" blurb remains, however. 
Even after I successfully send a reply.
Upon receiving a new Source message, however, the blurb goes away.

## STR
Close laptop. Lose connection. Blurb appears; error message shows. 
Connection returns, error mssg goes away. "Last Refresh" blurb remains. Sync happens. Nothing downloads, but icon animates. I send a message. It shows as successfully sent. "Last Refresh" Blurb remains. I send a reply. Blurb remains. 

## Expected
Close laptop. Lose connection. 
Error appears. Offline icon shows. Blurb appears. 
Connection restores, online icon shows, and error mssg goes away. 
Sync happens, with or without new stuff downloaded. 
Blurb goes away.

## Actual
Close laptop. Lose connection. Blurb appears; error message shows. 
Connection returns, error mssg goes away. "Last Refresh" blurb remains. Sync happens. Nothing downloads, but icon animates. I send a message. It shows as successfully sent. "Last Refresh" Blurb remains. I send a reply. Blurb remains. 

![image](https://user-images.githubusercontent.com/8262612/77495100-d3c44000-6e04-11ea-84c0-138a1320e96e.png)

**Comment by ninavizz** [comment] 2020-03-25 02:28
@creviera This is what I messaged you about, earlier. Not sure if it's how the feature is built, or a proper bug, so not labeling.

**Comment by eloquence** [comment] 2020-03-25 05:51
Cannot reproduce on current `git master`. I see no "Last Refresh" at all unless I'm in offline mode, otherwise it looks like this when there's a connection error:

![noconnection](https://user-images.githubusercontent.com/213636/77506006-16a10a80-6e3b-11ea-9918-9e3a16d418f9.png)

**Comment by eloquence** [comment] 2020-07-01 23:18
Will try to repro this once more with current nightlies.

**Comment by eloquence** [comment] 2020-07-02 01:11
The behavior in https://github.com/freedomofpress/securedrop-client/issues/1000#issuecomment-603654179 is still what I'm seeing, with July 1 nightly and 0.4.0-rc1 RPM in Qubes staging env. Closing this, @ninavizz please let us know if you see it again in recent builds.

**Closed by eloquence** 2020-07-02 01:11 UTC
Labels: needs/reproducing
