### ISSUE TITLE
When you start the client in offline mode unstarring still works

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#935] opened 2020-03-13 21:37 UTC
# STR

1. Make sure you have a starred source
2. Log into the client in offline mode
3. While offline, at any point during your session, click on the star to unstar the starred source

# Expected

The "must sign in" message and for starring to not work

# Actual

The "must sign in" message but starring does work

Note: This was happening on `master` before https://github.com/freedomofpress/securedrop-client/pull/933 was merged

**Comment by rmol** [comment] 2020-03-13 21:47
I think this is going to be fixed by #916.

**Comment by creviera** [comment] 2020-03-13 21:56
Looks like it is not fixed by #916 sadly :(

**Comment by redshiftzero** [comment] 2020-03-13 22:32
I just pulled latest master (7066e9b38ee8e214f8c668fced750f268d44382f) and for me behavior is as expected both when I start the client in offline mode and I start the client in online mode and then logout

**Comment by eloquence** [comment] 2020-03-13 22:36
I am also not able to reproduce this in a [0.2.3-deb](https://github.com/freedomofpress/securedrop-debian-packaging/releases/tag/0.2.3) prod build.

**Comment by creviera** [comment] 2020-03-13 22:39
Oops I just realized that I get the "You must sign in" error but starred sources can still be unstarred. Lemme show a gif...

**Comment by creviera** [comment] 2020-03-13 22:43
![Peek 2020-03-13 15-42](https://user-images.githubusercontent.com/4522213/76664374-60d3e300-6541-11ea-8316-cf76c12b69fd.gif)

**Comment by eloquence** [comment] 2020-03-13 22:44
Not able to see this in the prod build, but let me try in `master`

**Comment by eloquence** [comment] 2020-03-13 22:51
Yup, see the same behavior in `master` in Qubes.

**Comment by eloquence** [comment] 2020-03-13 22:57
I can reproduce the broken behavior on commit b2319715 (part of #872), but not before it.

**Closed** 2020-03-13 23:26 UTC
Labels: bug
