### ISSUE TITLE
Incorrect Timestamp

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-client#1017] opened 2020-03-26 23:13 UTC
## Description
As a journalist reporting for SuperFun Times, I opened my Client. 
I see Sources!
Everything is ordered correctly.
A new message comes in, from an existing Source—`reactionary ambrosia`.

![image](https://user-images.githubusercontent.com/8262612/77705110-0c3a5a00-6f7c-11ea-938a-3faa7f0d9c4c.png)

The timestamp in the Source Widget updates, but it does not update at the top of the Conversation Pane. The Source Widget's placement also remains the same—leaving a message updated today, beneath Sources last updated, yesterday.

Upon receiving a follow-up message from that same source (about COVID—and I'm sorry I couldn't get this w/o the tooltip), the Conversation Pane's header updated, but the Source Widget remained below the 2 Sources from the day before. 

![image](https://user-images.githubusercontent.com/8262612/77705237-5c192100-6f7c-11ea-91b1-4a71cb82091f.png)

## STR
1. Open client on `SuperFun` instance
2. Send a response from an existing source, who submitted more than a day before.
3. Observe dates.
4. Do it again.
5. Observe dates.

## Expected
When the Source sends a new message, their Widget should move to the top of the Source List, and the dates should both match as today's date in the Source Widget and the Conversation Pane Header.

**Comment by eloquence** [comment] 2020-03-26 23:54
This sounds like a repeat of #442.

**Comment by eloquence** [comment] 2020-04-02 21:27
@creviera I'll save you some time and see if I can repro this one on git `master`.

**Comment by eloquence** [comment] 2020-04-03 00:56
All existing conversations have the expected timestamps in both places, have created a new source and will log in again as that source tomorrow to see if that produces the behavior in the STR.

**Comment by eloquence** [comment] 2020-04-04 00:33
I'm unable to reproduce this issue, both in current prod install, and in git `master`. The source timestamp is correctly updated in both places. Before:

![time-1](https://user-images.githubusercontent.com/213636/78414404-bcd5d880-75d0-11ea-87fa-f25244e8fec4.png)

After:

![time-2](https://user-images.githubusercontent.com/213636/78414405-bd6e6f00-75d0-11ea-82f2-83fb1f1f9a09.png)

It's possible that this was resolved by #1013, which also ensured updated sources are placed at the top of the source list. @ninavizz let us know if you see this again in your current `staging` builds, will close in a few days if not.

**Comment by creviera** [comment] 2020-04-13 18:14
I am unable to reproduce, so am putting this on the backburner. We should consider closing.

**Closed by creviera** 2020-04-13 18:14 UTC
Labels: bug, needs/reproducing
