### ISSUE TITLE
[0.2.1-deb] Deleted source briefly re-appears as ghost

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-client#858] opened 2020-03-04 01:01 UTC
Encountered [during QA](https://github.com/freedomofpress/securedrop-workstation/issues/484).

After deleting a source just before a sync, I saw the source briefly re-appear for a few seconds. The ghost of the source did not have any messages or replies, and communicating with the ghost led to reply failures. The ghost source vanished after a few more seconds.

For cases like this, a pending deletion state (#534) would come in handy.

**Comment by creviera** [comment] 2020-03-05 02:37
Can you check if you can still reproduce now that https://github.com/freedomofpress/securedrop-client/pull/866 has been merged (also I haven't been able to repro this issue _yet_)?

**Comment by eloquence** [comment] 2020-03-05 07:52
I've not tested with #866 yet but I saw it again in the original release build today.

**Comment by creviera** [comment] 2020-03-05 18:34
ah good to know, i'll keep trying to repro today

**Comment by creviera** [comment] 2020-03-05 20:28
I just want to add my notes to this issue:

## Why should we avoid deleting the source from the sources table until the end of session?

```
1. A sync happens right before a source deletion on the server and the server response says the source exists
2. Deletion of source finishes on the server after the sync
3. The sync success handler will notice that we don't have that source in our local db, so it will think it's a new source and add it
4. The next sync gets a server response without the source (it no longer exists)
5. The sync success handler will notice that we have the source in our local db, so it will delete it.
```

This is an issue because we assume in the client code that a source from the server that we don't have stored in our local db is a new source that we need to add locally.

If instead of deleting the source locally we just updated its status to `DELETED` we would know that the source we get back from the server is just from an outdated response.


## When should we remove the source from the local sources table?

1. We could remove the `DELETED` source once we get a sync response with the source gone from the list we get back from the server. If there is a crash, then the next time the user logs in the sync will happen and it will remove any `DELETED` sources if the response shows them as missing

2. We could remove any `DELETED` sources on logout or login (if there was a crash).

**Comment by redshiftzero** [comment] 2020-03-05 21:34
Agree with your 1. So recapping a convo between @creviera @eloquence @ninavizz and I, we can:

1. When we click source delete, we immediately set the source to its pending state (per @ninavizz mockup in #534). 
2. When source deletion completes, we transition the source status from pending to deleted per your comment. The source deletion success callback deletes the source's files, messages, replies. At this point we'd no longer show the source in the source list (i.e. we need to filter by sources that are not marked as deleted).
3. The sync logic will only add new content for sources that are marked as not deleted locally (i.e. we should not add download jobs for their messages/replies). The source row will be deleted by this sync action.

And we could separate this into two changes:
1. Implement backend changes (resolves this item)
2. Display pending status in UI when source is in pending state (resolves #534)

**Comment by creviera** [comment] 2020-03-05 22:14
To explain this another way, there's no reason we would ever need to check the db to see if we need if we need to show a source as pending deletion before creating a source widget.

Also, removing the `DELETE_PENDING` db state means we don't have to check for it on login or logout to set it to `FAILED` or None or something. A source either exists, doesn't exist, or is in this `DELETED` state to fix the ghost issue.

**Comment by creviera** [comment] 2020-03-09 21:04
> So we should either not store state on that object or modify that behavior.

#893 modifies that behavior. Once it's merged we will only delete SourceWidget when the source is deleted, which resolves the issue you pointed out.

**Comment by redshiftzero** [comment] 2020-03-11 02:27
I agree - since we do not need to persist the pending status between sessions (the journalist will need to attempt to delete the source again manually in that scenario), we do not need to store it in the database after #893

**Closed** 2020-03-12 20:35 UTC
Labels: bug, release blocker
