### ISSUE TITLE
Incomplete localization ("last sync" time, source action menu, Export All warning modal)

### ISSUE THREAD

**Issue by rocodes** [freedomofpress/securedrop-client#1644] opened 2023-03-15 19:12 UTC
## Description

There are a few untranslated strings (see attached):
- The last refresh time ("x days ago", "just now") is in English
- The new Source Menu actions (Export All, Export Transcript, Print Transcript) are in English, as are the dividers (Files and Messages, Source Actions)
- The Export All warning modal, when not all files have been downloaded
- The date string still uses English month names and formatting (already known, documenting for completeness) 

## Steps to Reproduce

start the client, setting env var `LANG=pt_PT`

## Expected Behavior

Consistent (ish) translation

## Actual Behavior

See top left corner ("Just now") and right corner (source menu options and dividers)

![untranslated_client_options](https://user-images.githubusercontent.com/22777700/225417614-396014fc-786d-4dfa-9484-da8c45b212e9.png)

## Comments

Probably not a release blocker since language support so far is low. Just documenting.

**Comment by cfm** [comment] 2023-03-15 19:32
I'd argue this is not a bug, just a reality of:

1. in general, partial translation coverage, falling back to the English source strings _by design_; and
2. in general, our not (yet?) having committed to following the new [policy on supported languages](https://github.com/freedomofpress/securedrop-dev-docs/pull/35) during the pilot (or specifically for this release); and
3. in particular, #1548 being blocked on freedomofpress/securedrop#6483, among other things.

We can:

1. block the release on #1548 (I don't recommend this!);
2. revert #1531: disable `pt_PT` and `zh_Hans` pending #1548; or
3. ship `0.9.0-rc2` with the current (incomplete) translations.

In any case, we should revisit this (and [this question](https://docs.google.com/document/d/1Ny5Oz6MkeMysyPcuj4PNCzFobDtncfcQLyycFUDd_kY/edit?disco=AAAApBFWDvI)) in the release retrospective.

**Comment by gonzalo-bulnes** [comment] 2023-03-15 20:36
What @cfm said. Either option 2 or 3 seem fine to me.

In hindsight I should have called out that we were going with _option 3_ explicitly when we decided to leave #1548 out of the release scope. But _option 2_ also seems fine to me. (I'd too avoid _option 1_ until significant changes in the localization context.)

**Comment by gonzalo-bulnes** [comment] 2023-03-15 21:07
Complementing the above:

- I've added some missing documentation for the decision mentioned above (https://github.com/freedomofpress/securedrop-client/pull/1548#issuecomment-1470838217)
- I'd consider this to **not** be a blocker for [**0.9.0**](https://github.com/freedomofpress/securedrop-client/issues/1637) unless we change that decision.

What do you think @rocodes @cfm @zenmonkeykstop ?

**Comment by zenmonkeykstop** [comment] 2023-03-15 21:16
Voting to ship it, it's not ideal but not a blocker IMO.

**Comment by gonzalo-bulnes** [comment] 2023-03-21 05:39
> I'd argue this is not a bug, just a reality of […]

Since the situation described here is part of the normal development cycle, I'll close this issue.

**Closed** 2023-03-21 15:18 UTC
Labels: bug, localization
