### ISSUE TITLE
Support for opening hyperlinks in disp-vm

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-client#1270] opened 2021-07-20 20:31 UTC
## Problem
When a source shares a hyperlink with an org in SecureDrop, today, below is the experience Client users have. While this experience was recently enhanced by enabling users to copy/paste text from the SD Client, supporting a more streamlined workflow would be ideal.

https://user-images.githubusercontent.com/8262612/126391022-e27bf204-5190-424b-b4c0-276034ada900.MOV

## Solution
In user research conducted in support of the pilot, a feature to allow hyperlinks to be loaded into a disposable VM has been requested. A [sibling issue](In user research conducted in support of the pilot, a feature to allow hyperlinks to be loaded into a disposable VM has been requested.) has been created in the ux repo, for required ux stuff to support this (how will hyperlinks be displayed, and what might the broader experience look/act like for users?).

**Comment by eloquence** [comment] 2021-07-21 17:20
Duplicate of #1105.

**Closed by eloquence** 2021-07-21 17:20 UTC
Labels: ux
