### ISSUE TITLE
shrinking size of window can cause sources in the source list to disappear

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-client#613] opened 2019-11-08 14:21 UTC
# Description

When you decrease the size of the window, sources can disappear. I've observed this for two sources in the dev env, I decreased the size of the window at only the top (active) source stayed there, the second source disappeared.

# Steps to Reproduce

1. Log into client
2. Reduce size of window

# Expected behavior

All sources continue to appear in the source list

# Actual behavior

One source disappears from the source list

**Comment by deeplow** [comment] 2019-11-13 00:49
I think I've seen this one before. Just want to make sure this is the one.

I'm using i3 and when I maximise the window the following happens _sometimes_
![sd-pic](https://user-images.githubusercontent.com/47065258/68722982-2405d880-05af-11ea-9f2f-9676c77d2897.png)

The source is still on the list and can be selected but the text is not visible
![sd-pic2](https://user-images.githubusercontent.com/47065258/68723032-531c4a00-05af-11ea-841d-897d4e4ffc24.png)

After a while it fixed itself (probably an automatic refresh)
![sd-pic3](https://user-images.githubusercontent.com/47065258/68723054-64fded00-05af-11ea-8ed2-6e731ccb2be9.png)

**Comment by creviera** [comment] 2019-11-13 00:54
This bug was reintroduced after https://github.com/freedomofpress/securedrop-client/pull/330 was merged. Instead of using the default Qubes selection styling, we want to use our own, but there's this `show-decoration-selected:0` bug reported here: https://github.com/freedomofpress/securedrop-client/issues/331#issuecomment-487406667

**Comment by creviera** [comment] 2019-11-13 01:00
More specifically:

If you remove this line of code the issue is fixed:

https://github.com/freedomofpress/securedrop-client/blob/master/securedrop_client/gui/widgets.py#L840

But we need a better fix/ workaround that doesn't force us to use Qubes selection decoration style.

**Comment by creviera** [comment] 2019-11-13 18:36
closing because this is a duplicate of: https://github.com/freedomofpress/securedrop-client/issues/331
(I'll update its title to be more clear)

**Closed by creviera** 2019-11-13 18:36 UTC
Labels: bug, component/UI, help wanted
