### ISSUE TITLE
mutliple speech bubbles drawn on top of each other

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#851] opened 2020-03-03 17:52 UTC
# STR

(fill in here if someone manages to come up with reproducible steps)

At least once a day I see the ConversationView display multiple speech bubbles on top of each other. I haven't been able to create reproducible steps, but it seems more common when the client first starts up.

# Expected

One speech bubble per message with correct spacing between other bubbles.

# Actual

![Screenshot from 2020-03-03 09-15-01](https://user-images.githubusercontent.com/4522213/75803853-f1d1df80-5d33-11ea-9b4e-90196bda10a3.png)

**Comment by rmol** [comment] 2020-03-18 18:21
I think this may have also been fixed by #937. I cannot reproduce it on current master.

**Comment by redshiftzero** [comment] 2020-03-18 23:02
Yep I agree with @rmol, closing. If anyone sees during the next few days of QA, get loud and we'll take another look.

**Closed by redshiftzero** 2020-03-18 23:02 UTC
Labels: bug, needs/reproducing
