### ISSUE TITLE
Printing transcripts is broken in 0.10.0

### ISSUE THREAD

**Issue by legoktm** [freedomofpress/securedrop-client#1937] opened 2024-03-20 17:40 UTC
## Description

More details to come, see https://github.com/freedomofpress/securedrop-client/pull/1936 for now.

**Comment by rocodes** [comment] 2024-03-20 17:49
Thanks! 
More details: 

Print transcript was broken because the PrintTranscriptDialog was closed prematurely rather than relying on parent signals/slots on when to close the dialog. Closing the dialog too quickly killed the underlying QProcess, which was busy dispatching the print job. This is a regression that was fixed for the PrintDialog [here](https://github.com/freedomofpress/securedrop-client/blame/92725084ace1ca31d802011e5436c2d44c520d14/client/securedrop_client/gui/conversation/export/print_dialog.py#L32-L34), but PrintTranscriptDialog, which inherits from PrintDialog, still had the `dialog.close()`  call in it when it should have been removed.

**Closed** 2024-03-20 17:56 UTC
