### ISSUE TITLE
Elements misaligned in rendering

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-client#987] opened 2020-03-24 20:52 UTC
## Problem
Sad (albeit minor) UI regression in rendering from yesterday's nightly (060217).
![image](https://user-images.githubusercontent.com/8262612/77475834-a2348000-6dd6-11ea-8f69-9867c557db9c.png)

In both screenshots: see misalignment of Preview text and Source Name.

See broken `file widget` and placement of its first half, in this screenshot:
![image](https://user-images.githubusercontent.com/8262612/77475538-381bdb00-6dd6-11ea-8ce5-cef3c4523e8b.png)

See misalignment and too-low placement, in this screenshot:
![image](https://user-images.githubusercontent.com/8262612/77475589-4a961480-6dd6-11ea-9ef8-fd7e4b70d662.png)

**Comment by eloquence** [comment] 2020-03-24 21:03
That file size placement is a serious UX regression, will see if I can repro.

**Comment by eloquence** [comment] 2020-03-24 21:08
Can't repro the file size placement issue in the first screenshot in git `master` on non-Qubes. If you can reproduce this cleanly, @ninavizz, steps to reproduce it would be most helpful.

**Comment by eloquence** [comment] 2020-03-25 00:16
![misalign](https://user-images.githubusercontent.com/213636/77488578-fefe5d80-6e0b-11ea-9551-1fd0818b4f5e.png)

I've not seen file size misplacement as bad as in Nina's screenshot yet but this is as bad as it gets for me, and I see it in both `master` and 0.2.3-deb prod install, on Qubes. It seems to depend on the source -- the rendering is consistent per source, but for some of them it's just off by quite  bit.

**Comment by eloquence** [comment] 2020-03-25 00:30
Closing as duplicate of #694 but will cross-reference new screenshots.

**Comment by ninavizz** [comment] 2020-03-25 01:09
@eloquence I couldn't get it to reproduce in a new Source, either, FYI. It's just how the first new Source rendered, when I ran my client for the first time after last night's nightly, from the SuperFun instance.

**Comment by redshiftzero** [comment] 2020-03-30 23:12
folks are still reporting this

**Comment by creviera** [comment] 2020-04-02 00:56
I belive this should have been closed when its duplicate was closed?

**Comment by creviera** [comment] 2020-04-02 16:06
oh wait nvm I made a PR for this. whoops, already forgot.

**Closed** 2020-04-02 19:58 UTC
Labels: bug
