### ISSUE TITLE
Linespacing!

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-client#959] opened 2020-03-19 16:16 UTC
## Problem
Linespacing is a critical element in typesetting to optimise for legibility. Without it, the text on multi-line blocks of text (such as messages, and paragraphs) is less-legible; especially when the text is at a smaller size, such as on Preview snippets in the Source List.

To date we've had difficulties implementing this (per #865 and other issues), but have also discussed solution opportunities. 

## Solution
Figure-out and implement across all areas of code where specified. Critical areas include:
- Messages in Conversation Pane
- Preview snippets in Source List
- Text(s) on Print and Export flow start screens

**Comment by eloquence** [comment] 2021-12-10 00:15
Duplicate of the newer #1363, which has a bit more detail.

**Closed by eloquence** 2021-12-10 00:15 UTC
Labels: ux, Qt Investigation
