### ISSUE TITLE
Integrate basic single-file export using sd-export VM

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-client#526] opened 2019-08-07 06:08 UTC
We now have a basic export implementation using the sd-export workflow [documented](https://github.com/freedomofpress/securedrop-workstation) in the workstation README. Once remaining integration blockers are resolved (https://github.com/freedomofpress/securedrop-workstation/issues/281, https://github.com/freedomofpress/securedrop-workstation/issues/264, and https://github.com/freedomofpress/securedrop-workstation/issues/271), and we have a basic UI layout for per-file actions in place (#525), we should be ready to start on a lightweight integration:

- Add an "Export" action for each individual file as seen [in Zeplin](https://app.zeplin.io/project/5c807ea562f734bd2756b243/screen/5d1301b692a0cd04b141175d)
- If user clicks "Export", client initiates pre-flight checks
- If pre-flight checks suggest VM is not launched yet or no USB connected, show "Insert USB" dialog as shown in final print/export specs [in Zeplin](https://app.zeplin.io/project/5c807ea562f734bd2756b243)
- If pre-flight checks suggest we're ready to go, immediately initiate export
- Client shows error screens for each error state returned by the script (screen content to be vetted  in close collaboration with @ninavizz), otherwise shows success message

Out of scope for this issue:
- Handling currently unsupported error cases, e.g., pre-calculation of file size vs. diskspace
- Handling passphrases (passphrase can be hardcoded in config for now)
- Handling VeraCrypt vs. LUKS (VeraCrypt support is still pending)
- Handling multiple files
- Handling message export
- Handling >1 USB port

As always, splitting this into multiple PRs is up to the implementer, but all the above in-scope requirements should be addressed to fully resolve this issue.

**Comment by creviera** [comment] 2019-09-04 17:31
Quick notes - what im seeing right now (this could change since im actively testing export in qubes):

* when the usb port is reassigned a number or i accidentally plug the usb into the wrong port, the client will get back `ERROR_USB_CONFIGURATION` when running the `usb-test` preflight check
* when the port number matches what's in config.json, but the usb is not plugged in yet and the client triggers the`usb-test` preflight check, then `sd-export-usb` vm fails to start and freezes the client so the `usb-test` preflight check is not run (we cannot get back `USB_NOT_CONNECTED` error and respond.
* The client becomes inoperable for somewhere between 10 and 20 seconds while the `sd-export-usb` vm starts up
* The export vm is not being started during qubes startup (I thought this had been added at some point but haven't looked into this yet)
* when the client starts up with the usb drive plugged in, then when attemting to run `usb-test` preflight check qubes says it the vm failed to start. there is a barrage of qubes notification popups and some that immediately disappear and others that remain that sometimes are no longer relevant.
* when i reboot the machine with the usb stick plugged in, it automounts to the export vm, however the `usb-test` preflight check freezes the client, tihs is the command it freezes on `qvm-open-in-vm sd-export-usb /home/user/.securedrop_client/usb-test.ed-export`

will update here when there's more progress or information about my findings... once the steps to reproduce these issues above become clearer i can file issues

**Comment by creviera** [comment] 2019-09-04 19:08
when sd-export-usb starts, i see these popups with the error message:
`Domain sd-export-usb has failed to start: list.remove(x): x not in list`:

![signal-attachment-2019-09-04-115958](https://user-images.githubusercontent.com/4522213/64283189-cb112880-cf0b-11e9-8375-1bbfa9d977d0.jpeg)

To check that this is not only happening on my machine, run `qvm-open-in-vm sd-export-usb /home/user/.securedrop_client/usb-test.sd-export` in `sd-svs` when the usb is plugged in and when it's not plugged in.

Note: I ran the following commands before testing this:
```
make remove-sd-export
qvm-remove sd-export-template
make sd-export
```

(`make sd-export` is run with the usb stick plugged in and config.json has the correct usb port number)

**Comment by creviera** [comment] 2019-09-04 19:11
![one-attempt-to-start-sd-export-usb](https://user-images.githubusercontent.com/4522213/64283874-27c11300-cf0d-11e9-8181-13f96659468b.png)

**Comment by creviera** [comment] 2019-09-04 21:31
To get passed `Domain sd-export-usb has failed to start: list.remove(x): x not in list:` error:
1. kill qui-devices per https://github.com/QubesOS/qubes-issues/issues/4878#issuecomment-472175527
2. run `qvm-usb ls` with the usb device plugged in, see what its assigned number is (it was a new number for me)
3. update `config.json` to the correct usb device number
4. rerun `make sd-export`
5. start `sd-export` and no longer see a bunch of qube popup notifications

**Comment by eloquence** [comment] 2019-09-09 17:17
Cross-linking other potentially related upstream issue:
https://github.com/QubesOS/qubes-issues/issues/4849

**Comment by creviera** [comment] 2019-09-16 17:13
Linking to the most up-to-date design: https://projects.invisionapp.com/share/TNT1Q7XGH89#/screens

**Comment by creviera** [comment] 2019-09-23 16:42
Linking to the most up-to-date design: https://projects.invisionapp.com/share/WKTCW3J7B34#/screens/377942793

**Comment by creviera** [comment] 2019-10-31 21:44
- [x] Add an "Export" action for each individual file as seen [in Zeplin](https://app.zeplin.io/project/5c807ea562f734bd2756b243/screen/5d1301b692a0cd04b141175d)
- [x] If user clicks "Export", client initiates pre-flight checks
- [x] If pre-flight checks suggest VM is not launched yet or no USB connected, show "Insert USB" dialog as shown in final print/export specs [in Zeplin](https://app.zeplin.io/project/5c807ea562f734bd2756b243)
- [x] If pre-flight checks suggest we're ready to go, immediately initiate export
- [x] Client shows error screens for each error state returned by the script (screen content to be vetted  in close collaboration with @ninavizz), otherwise shows success message

The criteria is met here so I think this issue should be closed, unless I'm missing something?

UI polishing, UX-blocker discussions, post-beta feature ideas, and the bus id bug are all being tracked:
* #554 
* #556 
* #557 
* #558
* #560 
* and more! See https://github.com/freedomofpress/securedrop-client/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+export for a break down of 
* See https://github.com/freedomofpress/securedrop-export/issues for bus id and enhancement issues

**Comment by redshiftzero** [comment] 2019-10-31 21:45
agreed, let's close this

**Closed by redshiftzero** 2019-10-31 21:45 UTC
Labels: qubes, ux
