### ISSUE TITLE
JSONDecodeError: Expecting value: line 1 column 1

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#900] opened 2020-03-09 23:16 UTC
# STR
(I can't repro anymore but here's what I did)

1. start the server with 10 sources 
2. start the client 
3. add a couple new sources with files to download
4. download a file
5. delete a source from the original 10
6. delete one of the new sources

# Expected

For the new source to delete

# Actual

The error bar shows "Failed to delete source at server"

```
2020-03-09 16:02:43,108 - securedrop_client.gui.widgets:1185(launch) DEBUG: Deleting source 5f052611-5d28-4f20-86c3-c905f6ef1d6d
2020-03-09 16:02:43,109 - securedrop_client.queue:236(enqueue) DEBUG: Added DeleteSourceJob to main queue
2020-03-09 16:02:43,113 - urllib3.connectionpool:205(_new_conn) DEBUG: Starting new HTTP connection (1): localhost:8081
2020-03-09 16:02:43,143 - urllib3.connectionpool:393(_make_request) DEBUG: http://localhost:8081 "DELETE /api/v1/sources/5f052611-5d28-4f20-86c3-c905f6ef1d6d HTTP/1.1" 500 None
2020-03-09 16:02:43,144 - securedrop_client.queue:131(process) ERROR: JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-03-09 16:02:43,144 - securedrop_client.queue:132(process) DEBUG: Skipping job
```

**Comment by kushaldas** [comment] 2020-03-24 09:22
I am trying to reproduce this one. One point for a similar situation in future, have a look at the server logs. There might be some errors.

**Comment by kushaldas** [comment] 2020-03-24 09:46
I could not reproduce this in my timeboxed attempt, keeping it open it everyone comes online.

**Comment by eloquence** [comment] 2020-04-02 17:49
Closing until we see another repro.

**Closed by eloquence** 2020-04-02 17:49 UTC
Labels: bug, needs/reproducing
