### ISSUE TITLE
UI Polish: Sign Out button

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-client#850] opened 2020-03-03 17:51 UTC
## Problem
We have a client, woo!! It works, woo!! Time to polish some UI details. For this specific issue, the "Sign Out" option looks more like a tooltip or a menu option, than a button—which is very confusing for non-Linux/FOSS users to see, when clicking on the auth widget (because it's a very non-standard pattern).

## Solution
- [Click on Auth Widget](https://zpl.io/VOxOjMY)
- [Hover over Sign Out](https://zpl.io/V4z37WX)

**Comment by eloquence** [comment] 2020-03-20 03:59
@ninavizz Does the design here supersede the one in #285? I'm guessing yes, but if so, we should deprecate that recommendation in #285.

**Comment by ninavizz** [comment] 2020-03-23 21:28
@eloquence Yes! The solution in #285 was crafted before truncation was delved into, and the solution presented here better supports expanding truncated names. Will this be able to get some @ntoll love per chance?

**Comment by eloquence** [comment] 2020-03-25 20:13
This looks like a duplicate of #677, but I'll add the additional Zeplin link from the issue description there for reference.

**Closed by eloquence** 2020-03-25 20:13 UTC
