### ISSUE TITLE
Missing required package reference at the documentation

### ISSUE THREAD

**Issue by ultimatecoder** [freedomofpress/securedrop-client#74] opened 2018-10-26 15:06 UTC
* **Description:** [README.md](https://github.com/freedomofpress/securedrop-client/blob/master/README.md) file is mentioning steps to make the build and run tests. It is causing a reference error if [xvfb-run](https://packages.debian.org/sid/xvfb) package is not installed. The package **xvfb-run** is part of [xvfb](https://packages.debian.org/sid/xvfb) package. The documentation should mention [xvfb](https://packages.debian.org/sid/xvfb) as prerequisite for running the tests.

**Comment by ntoll** [comment] 2018-11-05 14:13
Duplicate of #84.

**Closed by ntoll** 2018-11-05 14:13 UTC
