### ISSUE TITLE
max size of window is too big in qubes 

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#1118] opened 2020-06-23 16:04 UTC
# Description

In Qubes, when you click the window resize button or double click the window titlebar, the window becomes too large for the screen.

See https://github.com/freedomofpress/securedrop-client/issues/1074#issuecomment-620171589

**Comment by eloquence** [comment] 2020-07-02 00:03
(Closing as duplicate of #1109, copied reference to comment)

**Closed by eloquence** 2020-07-02 00:03 UTC
Labels: bug
