### ISSUE TITLE
Potential crashes between source deletion and accessing source in the gui

### ISSUE THREAD

**Issue by sssoleileraaa** [freedomofpress/securedrop-client#906] opened 2020-03-11 01:47 UTC
# Description

If a sync comes back with deleted sources from the server we delete them locally and then call `update_sources` which will first remove all the source widgets then remove all the conversation widgets for those sources. If a message, reply, or file download job finishes before the source widget is destroyed then it will try to access source.uuid or source.collection in several places in the code and crash the app. I think there is also an issue with a user trying to open a file for the source at this time.

To prevent this type of crash we should only access the source db object when absolutely necessary. For instance, it's not necessary to store source on an object when we only need the uuid so we can find a source widget.

**Comment by creviera** [comment] 2020-03-19 20:51
Here's a list of areas in the code that need attention regarding possible crashes due to trying to access data on a deleted source without catching the exception:

1. `update call in constructor that can raise`: https://github.com/freedomofpress/securedrop-client/blob/master/securedrop_client/gui/widgets.py#L1138
2. `StarToggleButton` - my current WIP PR around starring removed the reference already
3. https://github.com/freedomofpress/securedrop-client/blob/78d1bbe895b1e09b65f9df3f16dfbfc87527afbe/securedrop_client/gui/widgets.py#L1361
4. `ConversationView`: https://github.com/freedomofpress/securedrop-client/blob/master/securedrop_client/gui/widgets.py#L2916
5. `on_reply_sent`: https://github.com/freedomofpress/securedrop-client/blob/master/securedrop_client/gui/widgets.py#L3100
6. `SourceConversationWrapper`: https://github.com/freedomofpress/securedrop-client/blob/master/securedrop_client/gui/widgets.py#L3125
7. `on_source_change`: https://github.com/freedomofpress/securedrop-client/blob/master/securedrop_client/gui/widgets.py#L714
8. `SourceLists.update`: https://github.com/freedomofpress/securedrop-client/blob/master/securedrop_client/gui/widgets.py#L918
9. `DeleteSourceMessageBox`:  https://github.com/freedomofpress/securedrop-client/blob/78d1bbe895b1e09b65f9df3f16dfbfc87527afbe/securedrop_client/gui/widgets.py#L1368
10. `ReplyBox`: https://github.com/freedomofpress/securedrop-client/blob/78d1bbe895b1e09b65f9df3f16dfbfc87527afbe/securedrop_client/gui/widgets.py#L3271

Some of these links take you to areas of the code where there are multiple instances of the issue, so look around for `source.` to make sure you get em all. Also I might have missed some in the list above.

**Comment by creviera** [comment] 2020-03-20 16:55
Numbers: 1, 2, and 8 have PRs. The rest are still up for grabs.

**Comment by creviera** [comment] 2020-03-26 23:04
Adding a new crasher to the list for our new scheduler code to add sources, saw this just now:

```
Traceback (most recent call last):
  File "/home/creviera/workspace/freedomofpress/securedrop-client/securedrop_client/gui/widgets.py", line 1004, in schedule_source_management
    new_source = SourceWidget(self.controller, source)
  File "/home/creviera/workspace/freedomofpress/securedrop-client/securedrop_client/gui/widgets.py", line 1220, in __init__
    self.update()
  File "/home/creviera/workspace/freedomofpress/securedrop-client/securedrop_client/gui/widgets.py", line 1227, in update
    self.controller.session.refresh(self.source)
  File "/home/creviera/workspace/freedomofpress/securedrop-client/.venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1675, in refresh
    "Could not refresh instance '%s'" % instance_str(instance)
sqlalchemy.exc.InvalidRequestError: Could not refresh instance '<Source at 0x7f04fd010790>'
```

**Comment by eloquence** [comment] 2020-03-27 21:43
We discussed today that a naive try/catch strategy around all UI access to widgets that may be tied to deleted database object is probably the best first way to safeguard this. We'll likely not get to this before Monday, but it's one of the highest priority known areas that can cause crashes, so tracking as release blocker.

**Comment by eloquence** [comment] 2020-04-02 21:24
Implementing the `try/catch` strategy mentioned above is a goal for the 4/2-4/15 sprint; the more comprehensive approach in #967 can be revisited at a later time.

**Comment by creviera** [comment] 2020-04-02 21:50
(hit this again today after deleting some sources server-side and starting the client: https://github.com/freedomofpress/securedrop-client/issues/906#issuecomment-604731431)

**Comment by eloquence** [comment] 2020-04-22 22:46
Deferring to near-term backlog as it's not been a significant issue for pilot installs so far. We'll revisit this in the next sprint (after the current 4/22-5/6 sprint); given that we do know that there's crash potential here, I do think it should go into 0.2.1/0.3.0 at the latest.

**Comment by creviera** [comment] 2020-05-05 18:03
We saw during the pilot that a [new piece of code that was added after this issue was opened](https://github.com/freedomofpress/securedrop-client/blob/505504084dd65a73d70a2c53322dc799cb2f7983/securedrop_client/gui/widgets.py#L1010) caused a segfault. The reason is that we access `last_updated` on the source db object without making sure it's valid: https://github.com/freedomofpress/securedrop-client/blob/505504084dd65a73d70a2c53322dc799cb2f7983/securedrop_client/gui/widgets.py#L907-L908

This can be added as part of # 8 in [the list](https://github.com/freedomofpress/securedrop-client/issues/906#issuecomment-601410639) above.

**Comment by eloquence** [comment] 2020-06-03 20:48
For the 6/3-6/17 sprint, @creviera has agreed to take a time-boxed stab at this to make an initial round of stability improvements, aiming for 8 hours (that should ideally include review, so I recommend making the implementation time-box shorter).

**Comment by creviera** [comment] 2020-06-23 19:52
Update on the progress of this issue:

# What's been fixed?
`1.` :heavy_check_mark:**DONE in https://github.com/freedomofpress/securedrop-client/pull/1114** 
  `SourceWidget.update` raises exception and callers don't catch it causing the app to crash
   * add-source scheduler (STR in https://github.com/freedomofpress/securedrop-client/issues/1117)
   * in the constructor: https://github.com/freedomofpress/securedrop-client/blob/f1e935ce86f1cdebf98bcf95e6c36d465484163e/securedrop_client/gui/widgets.py#L1175

`2.` :heavy_check_mark:**DONE in https://github.com/freedomofpress/securedrop-client/pull/952**
  `StarToggleButton`

`8.` :heavy_check_mark:**DONE in https://github.com/freedomofpress/securedrop-client/pull/1114** 
   * `uuid` in `SourceLists.update`: https://github.com/freedomofpress/securedrop-client/blob/f1e935ce86f1cdebf98bcf95e6c36d465484163e/securedrop_client/gui/widgets.py#L932
   * `last_updated` in `SourceLists.update` when source widgets are reordered (STR in https://github.com/freedomofpress/securedrop-client/issues/1116)

`12.` :heavy_check_mark:**DONE in https://github.com/freedomofpress/securedrop-client/pull/964**
  `set_snippet`

`13.` :heavy_check_mark:**DONE in https://github.com/freedomofpress/securedrop-client/pull/1114** 
  `schedule_source_management`: https://github.com/freedomofpress/securedrop-client/blob/97ce5bb690c26f8ffcdf473e66241eb053652db4/securedrop_client/gui/widgets.py#L1005

# What's left?
`3.` `DeleteSourceMessageBox`: https://github.com/freedomofpress/securedrop-client/blob/f1e935ce86f1cdebf98bcf95e6c36d465484163e/securedrop_client/gui/widgets.py#L1414
`4.` `ConversationView`: https://github.com/freedomofpress/securedrop-client/blob/f1e935ce86f1cdebf98bcf95e6c36d465484163e/securedrop_client/gui/widgets.py#L3005
`5.` `on_reply_sent`: https://github.com/freedomofpress/securedrop-client/blob/f1e935ce86f1cdebf98bcf95e6c36d465484163e/securedrop_client/gui/widgets.py#L3149
`6.` `SourceConversationWrapper`: https://github.com/freedomofpress/securedrop-client/blob/f1e935ce86f1cdebf98bcf95e6c36d465484163e/securedrop_client/gui/widgets.py#L3174
`7.` `on_source_change`: https://github.com/freedomofpress/securedrop-client/blob/f1e935ce86f1cdebf98bcf95e6c36d465484163e/securedrop_client/gui/widgets.py#L735
`9.` `DeleteSourceMessageBox`:  https://github.com/freedomofpress/securedrop-client/blob/78d1bbe895b1e09b65f9df3f16dfbfc87527afbe/securedrop_client/gui/widgets.py#L1368
`10.` `ReplyBox`: https://github.com/freedomofpress/securedrop-client/blob/78d1bbe895b1e09b65f9df3f16dfbfc87527afbe/securedrop_client/gui/widgets.py#L3271
`11.` `SourceProfileShortWidget`: https://github.com/freedomofpress/securedrop-client/blob/f1e935ce86f1cdebf98bcf95e6c36d465484163e/securedrop_client/gui/widgets.py#L3650

**Comment by eloquence** [comment] 2020-06-24 18:21
Thanks @creviera for the writeup. Since you've addressed the issues which were straightforward to reproduce and similar to reports we've heard from prod users, we've agreed to defer additional work on this for now, but will pick this issue up again and leave it open for tracking purposes.

**Comment by zenmonkeykstop** [comment] 2024-08-15 18:53
Closing, looks like it was addressed. May reopen as part of a future sync/data model milestone.

**Closed by zenmonkeykstop** 2024-08-15 18:53 UTC
Labels: bug, sync
