### ISSUE TITLE
Messages/replies cut off when sent together with files

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-client#998] opened 2020-03-25 02:09 UTC
## Description
When I send a lot of text as a source, the Client shows only some of that text as the received message. :((

## STR
1. Send a 480cc message to the SuperFun instance, as a source. 
- Either as a follow-up message from an existing Source, or as a new Source. 
- Either with or without a file.

I sent the following:

> Hello, and thank you for participating in the SecureDrop Workstation’s pilot. Below is a survey to collect some basic information about your skills and experience. 
> 
> This information will only be shared among the user research and support teams (so, 5 individuals, total). If you previously filled-out a similar survey for a past research effort, we ask that you please take a moment to complete this one—as we do not retain individual survey responses past each study’s completion.
2. Check Source convo in client on workstation.

## Expected
Complete text of message shows in client.
![image](https://user-images.githubusercontent.com/8262612/77494025-e5581880-6e01-11ea-8d8b-277a63b91a88.png)

## Actual
Message cut-off after the word `research`
![image](https://user-images.githubusercontent.com/8262612/77494347-c1490700-6e02-11ea-95f7-0906923b9f26.png)

**Comment by eloquence** [comment] 2020-03-25 05:41
I'm unable to reproduce this issue either in git `master` or in `0.2.3-deb` (prod build), but note that both of those versions are different from your nightly. I'm able to receive long messages without cut-off.

![longmessages](https://user-images.githubusercontent.com/213636/77505441-8615fa80-6e39-11ea-93c2-116fc62eae54.png)

**Comment by rocodes** [comment] 2020-03-30 22:50
I was able to repro this and found that both the source message and a long reply could be truncated/cut off.

I was also able to repro some inconsistency with this--on a subsequent run of the client, more of the messages were available (2 lines), but some was still truncated, and some long messages are not truncated at all. 

![multiline_2](https://user-images.githubusercontent.com/22777700/77969211-3a3ed780-72b7-11ea-9c26-0a82a66aa28a.png)
![multiline_3](https://user-images.githubusercontent.com/22777700/77969214-3b700480-72b7-11ea-812e-cc90df1969b4.png)

**Comment by rocodes** [comment] 2020-03-30 22:51
and my first one (with only 1 line showing) was https://user-images.githubusercontent.com/22777700/77966868-f39aae80-72b1-11ea-8678-1bd9767f5fc0.png

**Comment by redshiftzero** [comment] 2020-03-30 22:52
I can repro by repeating `0123456789abcdef0123456789abcdef0123456789abcdef` with no whitespaces: 

![Screen Shot 2020-03-30 at 6 51 35 PM](https://user-images.githubusercontent.com/7832803/77969356-8f7ae900-72b7-11ea-863c-a9715dc506e3.png)

**Comment by redshiftzero** [comment] 2020-03-30 22:57
there might be other issues, but at least we're seeing a regression from https://github.com/freedomofpress/securedrop-client/issues/815

**Comment by rocodes** [comment] 2020-03-30 23:24
**STR: Truncation of messages for both source and journalist related to attachment submissions**
1. As a source: 
Submit a long message containing whitespaces. Observe it not be truncated.  
2. As a journalist: Submit a long reply containing whitespaces. Observe it not be truncated. 
3. As a source: submit a message and an attachment.
4. As a journalist: observe truncation of previously non-truncated messages in the UI, as well as new replies

**Comment by creviera** [comment] 2020-03-30 23:35
I'm able to repro. Thank you for this STR!

**Comment by redshiftzero** [comment] 2020-03-30 23:38
After following that STR (this was with my client a reduced size), I don't see the truncation like https://github.com/freedomofpress/securedrop-client/issues/998#issuecomment-606293087, instead: 

![Screen Shot 2020-03-30 at 7 35 57 PM](https://user-images.githubusercontent.com/7832803/77971848-cd7b0b80-72bd-11ea-8da9-ab4068a8d496.png)

but I do see another (also bad) behavior, squished message bubbles:

![Screen Shot 2020-03-30 at 7 36 02 PM](https://user-images.githubusercontent.com/7832803/77971866-d9ff6400-72bd-11ea-934b-2d9eec69cfc9.png)

**Comment by rocodes** [comment] 2020-03-30 23:46
> **STR: Truncation of messages for both source and journalist related to attachment submissions**
> 
> 1. As a source:
>    Submit a long message containing whitespaces. Observe it not be truncated.
> 2. As a journalist: Submit a long reply containing whitespaces. Observe it not be truncated.
> 3. As a source: submit a message and an attachment.
> 4. As a journalist: observe truncation of previously non-truncated messages in the UI, as well as new replies
> 
> ![str_1_normal_replies](https://user-images.githubusercontent.com/22777700/77971981-25197700-72be-11ea-974c-435b0a2e38a0.png)
> ![str_2_truncated](https://user-images.githubusercontent.com/22777700/77971982-26e33a80-72be-11ea-8cbf-9c7f06c2d7fc.png)

A further update is that, if I resize the client window (was previously full-screened in the screenshots above), it redraws such that:
- less of the text is truncated
- the "download file size" is not placed above the attachment name/download button
![window_resized](https://user-images.githubusercontent.com/22777700/77972360-1a131680-72bf-11ea-851f-51f62dd31135.png)
 (which may be related to text/bubble being truncated).

**Comment by eloquence** [comment] 2020-03-31 00:15
Retitled this issue for clarity, and reopened #815; these two issues can be resolved independently, and this one is higher priority.

For the record, I can reproduce this issue outside Qubes as well, and observe similarly different rendering outcomes depending on client window size.

**Comment by conorsch** [comment] 2020-03-31 00:23
The STR that @rocodes provided were spot-on. Following those STR, was able to reproduce on test hardware, running securedrop-client v0.1.5 & securedrop-workstation-dom0-config v0.2.4.

**Closed** 2020-03-31 10:37 UTC
Labels: bug

**Comment by creviera** [comment] 2020-04-02 00:15
"eloquence moved this from I am a temporary column, ignore me to Done"

should i ignore this whole thing?

**Comment by eloquence** [comment] 2020-04-02 00:26
Sorry, use of temporary columns is to ensure that GitHub does not archive the most recent issues when using the "Archive all" feature. Will use a more descriptive name in future.
